/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PostRouteRouteImport } from './routes/post/route'
import { Route as HeroRouteRouteImport } from './routes/hero/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PostListRouteImport } from './routes/post/list'

const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRouteRoute = PostRouteRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroRouteRoute = HeroRouteRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostRouteRoute,
} as any)
const PostListRoute = PostListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PostRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hero': typeof HeroRouteRoute
  '/post': typeof PostRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/collect': typeof CollectRoute
  '/post/list': typeof PostListRoute
  '/post/': typeof PostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hero': typeof HeroRouteRoute
  '/about': typeof AboutRoute
  '/collect': typeof CollectRoute
  '/post/list': typeof PostListRoute
  '/post': typeof PostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hero': typeof HeroRouteRoute
  '/post': typeof PostRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/collect': typeof CollectRoute
  '/post/list': typeof PostListRoute
  '/post/': typeof PostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hero'
    | '/post'
    | '/about'
    | '/collect'
    | '/post/list'
    | '/post/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hero' | '/about' | '/collect' | '/post/list' | '/post'
  id:
    | '__root__'
    | '/'
    | '/hero'
    | '/post'
    | '/about'
    | '/collect'
    | '/post/list'
    | '/post/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroRouteRoute: typeof HeroRouteRoute
  PostRouteRoute: typeof PostRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CollectRoute: typeof CollectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero': {
      id: '/hero'
      path: '/hero'
      fullPath: '/hero'
      preLoaderRoute: typeof HeroRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/post/list': {
      id: '/post/list'
      path: '/list'
      fullPath: '/post/list'
      preLoaderRoute: typeof PostListRouteImport
      parentRoute: typeof PostRouteRoute
    }
  }
}

interface PostRouteRouteChildren {
  PostListRoute: typeof PostListRoute
  PostIndexRoute: typeof PostIndexRoute
}

const PostRouteRouteChildren: PostRouteRouteChildren = {
  PostListRoute: PostListRoute,
  PostIndexRoute: PostIndexRoute,
}

const PostRouteRouteWithChildren = PostRouteRoute._addFileChildren(
  PostRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroRouteRoute: HeroRouteRoute,
  PostRouteRoute: PostRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CollectRoute: CollectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
